version: '3'

services:
  backend:
    image: jupyter/pyspark-notebook
    container_name: pyspark_notebook
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./backend:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=ipython3
      - GRANT_SUDO=yes
      - NB_GID=100
      - GEN_CERT=yes
    user: root

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
